//
// AdditionalPropertiesClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdditionalPropertiesClass: Codable, Hashable {

    public var mapProperty: [String: String]?
    public var mapOfMapProperty: [String: [String: String]]?

    public init(mapProperty: [String: String]? = nil, mapOfMapProperty: [String: [String: String]]? = nil) {
        self.mapProperty = mapProperty
        self.mapOfMapProperty = mapOfMapProperty
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mapProperty = "map_property"
        case mapOfMapProperty = "map_of_map_property"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mapProperty, forKey: .mapProperty)
        try container.encodeIfPresent(mapOfMapProperty, forKey: .mapOfMapProperty)
    }
}
