//
// Apple.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Apple: Codable, Hashable {

    public var cultivar: String?

    public init(cultivar: String? = nil) {
        self.cultivar = cultivar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cultivar
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cultivar, forKey: .cultivar)
    }
}
