//
// AppleReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppleReq: Codable, Hashable {

    public var cultivar: String
    public var mealy: Bool?

    public init(cultivar: String, mealy: Bool? = nil) {
        self.cultivar = cultivar
        self.mealy = mealy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cultivar
        case mealy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cultivar, forKey: .cultivar)
        try container.encodeIfPresent(mealy, forKey: .mealy)
    }
}
