//
// Foo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Foo: Codable, Hashable {

    public var bar: String? = "bar"

    public init(bar: String? = "bar") {
        self.bar = bar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bar
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bar, forKey: .bar)
    }
}
