//
// FruitReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum FruitReq: Codable {
    case typeAppleReq(AppleReq)
    case typeBananaReq(BananaReq)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAppleReq(let value):
            try container.encode(value)
        case .typeBananaReq(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AppleReq.self) {
            self = .typeAppleReq(value)
        } else if let value = try? container.decode(BananaReq.self) {
            self = .typeBananaReq(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of FruitReq"))
        }
    }
}

