//
// GmFruit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GmFruit: Codable, Hashable {

    public var color: String?
    public var cultivar: String?
    public var lengthCm: Double?

    public init(color: String? = nil, cultivar: String? = nil, lengthCm: Double? = nil) {
        self.color = color
        self.cultivar = cultivar
        self.lengthCm = lengthCm
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case color
        case cultivar
        case lengthCm
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(cultivar, forKey: .cultivar)
        try container.encodeIfPresent(lengthCm, forKey: .lengthCm)
    }
}
