//
// HealthCheckResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Just a string to inform instance is up and running. Make it nullable in hope to get it as pointer in generated model. */
public struct HealthCheckResult: Codable, Hashable {

    public var nullableMessage: String?

    public init(nullableMessage: String? = nil) {
        self.nullableMessage = nullableMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nullableMessage = "NullableMessage"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nullableMessage, forKey: .nullableMessage)
    }
}
