//
// InlineResponseDefault.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InlineResponseDefault: Codable, Hashable {

    public var string: Foo?

    public init(string: Foo? = nil) {
        self.string = string
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case string
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(string, forKey: .string)
    }
}
