//
// Mammal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Mammal: Codable {
    case typeWhale(Whale)
    case typeZebra(Zebra)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeWhale(let value):
            try container.encode(value)
        case .typeZebra(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(Whale.self) {
            self = .typeWhale(value)
        } else if let value = try? container.decode(Zebra.self) {
            self = .typeZebra(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of Mammal"))
        }
    }
}

