//
// OuterEnumInteger.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OuterEnumInteger: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
