//
// OuterEnumDefaultValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OuterEnumDefaultValue: String, Codable, CaseIterable {
    case placed = "placed"
    case approved = "approved"
    case delivered = "delivered"
}
