//
// Whale.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Whale: Codable, Hashable {

    public var hasBaleen: Bool?
    public var hasTeeth: Bool?
    public var className: String

    public init(hasBaleen: Bool? = nil, hasTeeth: Bool? = nil, className: String) {
        self.hasBaleen = hasBaleen
        self.hasTeeth = hasTeeth
        self.className = className
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hasBaleen
        case hasTeeth
        case className
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hasBaleen, forKey: .hasBaleen)
        try container.encodeIfPresent(hasTeeth, forKey: .hasTeeth)
        try container.encode(className, forKey: .className)
    }
}
